spring.application.name=intern-work-backend

# ?? ?? (?? 8080)
server.port=8080

# DB ??
#spring.datasource.url=jdbc:mysql://localhost:3306/?????????serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=????
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis ??
# XML ?? ??
mybatis.mapper-locations=classpath:mapper/**/*.xml

# domain ??? ??
mybatis.type-aliases-package=com.mars.internworkbackend.domain

# DB ?? user_name ? Java ?? userName ?? ??
mybatis.configuration.map-underscore-to-camel-case=true

# ???? SQL ??? ??
logging.level.com.mars.internworkbackend.mapper=DEBUG